# SERVER CONFIGURATION
server:
  servlet:
    context-path: /
  port: 8080
  shutdown: "graceful"
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 32
      io: 4

# ACTUATOR CONFIGURATION
management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /

# SPRING CONFIGURATION
spring:
  application:
    name: @project.name@
    version: @project.version@
  main:
    banner-mode: "off"
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  metrics:
    web:
      server:
        auto-time-requests: true
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      "[hibernate.connection.handling_mode]": DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION

# OPEN API CONFIGURATION
springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  override-with-generic-response: false
  paths-to-exclude: /**/api-docs,/swagger-resources/**
  swagger-ui:
    path: /

# LOGGING CONFIGURATION
logging:
  level:
    ROOT: INFO
    br.com.multidatasources: INFO
  appender: CONSOLE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %X{X-Request-ID} %highlight(%-5level) %magenta([%t]) %msg%n"

# DATABASE SCHEMA PROPERTIES
schema:
  name: billionaires
  user: root
  pass: root

# DATABASE MASTER PROPERTIES
master:
  datasource:
    host: localhost
    url: jdbc:mysql://${master.datasource.host}:3306/${schema.name}?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: ${schema.user}
    password: ${schema.pass}

# DATABASE REPLICA PROPERTIES
replica:
  datasource:
    host: localhost
    url: jdbc:mysql://${replica.datasource.host}:3307/${schema.name}?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: ${schema.user}
    password: ${schema.pass}

# FLYWAY PROPERTIES
flyway:
  schema-name: ${schema.name}
  baseline-on-migrate: true
  locations:
    - classpath:db/migration
    - classpath:db/test-data

# AOP PROPERTIES
open-telemetry:
  aop:
    enabled: true
