# ACTUATOR CONFIGURATION
management:
  metrics:
    otlp:
      metrics:
        export:
          url: host.docker.internal:4317

# DATABASE MASTER PROPERTIES
master:
  datasource:
    host: host.docker.internal

# DATABASE REPLICA PROPERTIES
replica:
  datasource:
    host: host.docker.internal
